Implemented updates for backend usage
waldo-vision/waldo pull request #4
Opened 2022-11-15 22:48 UTC by b3kN

- Updated createFootage to parse and save clips
  - TODO: Validate download format from YouTube
- Implemented Python script for testing
  - Verification required on 30 vs 60 fps
- Merged in the web branch and previous changes to master
- Implemented logic to use exported next application in production (pnpm start)
- Implemented logic to use dev systems (pnpm dev)
- Implemented basic OpenAPI documentation page for backend API

2022-11-15 23:22 UTC, Huskydog9988 approved these changes

2022-11-15 23:22 UTC, Huskydog9988 commented on apps/backend/package.json
> +    "start": "NODE_ENV=production ts-node dist/index.js",
just a note, this prevents windows devs from using these scripts, we should proably be providing dev containers in this case, or some other reasonable substitute.

2022-11-15 23:22 UTC, Huskydog9988 commented on apps/backend/src/services/clips.ts
> +  const pyPro = spawn('python3', ['autoClip.py', 'test-new.mp4', 'clips', '1']);
what does the python code exactly do in relation to this?

2022-11-15 23:22 UTC, Huskydog9988 commented on apps/web/additional.d.ts
> +  }
am i missing something here?

2022-11-15 23:22 UTC, Huskydog9988 commented on apps/web/components/Footer.tsx
> +      src="/android-chrome-256x256.png"
in the future, can we switch to svg? (it scales better plus smaller file size)

2022-11-15 23:22 UTC, Huskydog9988 commented on apps/web/context/GlobalContext.tsx
> +});
i assume next auth populates this?

2022-11-15 23:22 UTC, Huskydog9988 commented on apps/web/pages/_app.tsx
> +}
i assume this is gonna pull from apps/web/context/GlobalContext.tsx in the future?

2022-11-15 23:22 UTC, Huskydog9988 commented on apps/web/tsconfig.json
> +, "pages/api/auth/[...nextauth].js"  ],
that looks like a type error

2022-11-15 23:22 UTC, Huskydog9988 commented on package.json
> +    "npm": "^9.1.1"
i don't think this is right

2022-11-15 23:22 UTC, Huskydog9988 commented on packages/ui/package.json
> +  "license": "MIT",
wrong license

2022-11-15 23:22 UTC, Huskydog9988 commented on turbo.json
> +      "env": ["PORT", "HOST", "DB_URL", "FS_LOCATION", "NODE_ENV"]
no cache?

2022-11-15 23:22 UTC, Huskydog9988 commented on apps/backend/src/controllers/footage.controller.ts
> +      parseClips(footageId, `${footageId}.mp4`);
comment?

2022-11-15 23:23 UTC, b3kN commented on .github/CODEOWNERS
> +/windowsforms/** @adegeo @dotnet/dotnet-winforms
Copy pasta - It has been removed

2022-11-15 23:23 UTC, b3kN commented on apps/backend/package.json
> +    "start": "NODE_ENV=production ts-node dist/index.js",
True - WSL ftw

2022-11-15 23:26 UTC, b3kN commented on package.json
> +    "npm": "^9.1.1"
https://github.com/waldo-vision/waldo/blob/web/package.json

2022-11-15 23:29 UTC, Huskydog9988 commented on package.json
> +    "npm": "^9.1.1"
yea, these are in `./package.json`, they should be in the `app/web/package.json` (i presume)

2022-11-15 23:30 UTC, b3kN commented on package.json
> +    "npm": "^9.1.1"
For sure, it was merged in but I hadn't attended to any web yet. I can fix this up quick

2022-11-15 23:30 UTC, b3kN commented on apps/web/additional.d.ts
> +  }
I'll clean this up

2022-11-15 23:33 UTC, Huskydog9988 commented on apps/web/additional.d.ts
> +  }
i assumed this had something to do with public env vars, but i guess i was wrong?

2022-11-15 23:35 UTC, b3kN commented on apps/web/additional.d.ts
> +  }
To be honest I'm not sure what it is being used for yet, but I figured the namespace didn't need to be declared twice

2022-11-15 23:43 UTC, b3kN commented on apps/backend/autoClip.py
> +"""
No doubt - I have my initial draft for the basic backend items: https://gist.github.com/b3kN/bef6d8f38a8417be7bc69d5360750e95

I need to update a few things and include the detailed expectations

2022-11-15 23:49 UTC, b3kN commented on apps/backend/src/services/clips.ts
> +  const pyPro = spawn('python3', ['autoClip.py', 'test-new.mp4', 'clips', '1']);
Well test-new.mp4 was my happy path, so I'll get that corrected. I will provide some notes in the comments for this section and the python script later. 

The python script gathers clips around the killshots found in CSGO footage based on the killfeed in the view. It grabs the frames around and including the kill shot into trimmed images to use in sequence for the AI model building. The node logic then stores the files into the pre-determined storage location from the env.

Related Task: https://github.com/waldo-vision/waldo.footage.collection/issues/9

For the short term, this fulfills the initial clip creation requirements:
```
Clip collection requirements:

1. Validate CS:GO footage
2. Create clips on kill shots
3. Clips should be cropped to 256x256 around the crosshair 
```

2022-11-15 23:56 UTC, Huskydog9988 commented on apps/backend/src/services/clips.ts
> +  const pyPro = spawn('python3', ['autoClip.py', 'test-new.mp4', 'clips', '1']);
thanks, hopefully we can get to commenting later, ik i haven't been great at it

2022-11-15 23:58 UTC, Huskydog9988 approved these changes

2022-11-15 23:58 UTC, Huskydog9988 commented on packages/eslint-config-custom/package.json
> +  "license": "MDL",
```suggestion
  "license": "MPL-2.0",
```

2022-11-16 00:01 UTC, Huskydog9988 approved these changes

2022-11-16 08:48 UTC, tsundDEV commented on apps/web/components/Navbar.tsx
> +  },
Remove Upload in navigation

2022-11-16 08:49 UTC, tsundDEV commented on apps/web/pages/index.tsx
> +            </Button>
Add functionality to buttons

2022-11-16 08:49 UTC, tsundDEV requested changes
**Front end Changes**

- Remove the upload in navigation
- Add functionallity to the discord button on the modal

2022-11-17 13:53 UTC, merged