Codebase -> main
waldo-vision/waldo pull request #61
Opened 2022-12-29 22:47 UTC by ceriddenn

Merge wip/web-rework (latest updated cb) into main

2022-12-29 23:16 UTC, Huskydog9988 requested changes

2022-12-29 23:16 UTC, Huskydog9988 commented on apps/web/additional.d.ts
> +    UPSTASH_REDIS_REST_URL: string;
there are other items that are duplicated, but im not gonna remove these in a pr

2022-12-29 23:16 UTC, Huskydog9988 commented on apps/web/components/TurnstileWidget.tsx
> +          siteKey={'1x00000000000000000000AA'}
use an env var here?

2022-12-29 23:16 UTC, Huskydog9988 commented on apps/web/components/dashboard/site/Maintenance.tsx
> +      });
more as stuff, can this get removed in a pr? (its also down below)

2022-12-29 23:16 UTC, Huskydog9988 commented on apps/web/components/dashboard/status/Account.tsx
> +      });
not very clear what 'change' is

2022-12-29 23:16 UTC, Huskydog9988 commented on apps/web/components/dashboard/status/Maintenance.tsx
> +        maintenance: data?.maintenance as boolean,
more as

2022-12-29 23:16 UTC, Huskydog9988 commented on apps/web/components/dashboard/status/Upload.tsx
> +      });
more change is a num

2022-12-29 23:16 UTC, Huskydog9988 commented on apps/web/components/dashboard/status/WaldoSite.tsx
> +    } else if (change == 1) {
change = num

2022-12-29 23:16 UTC, Huskydog9988 commented on apps/web/next.config.js
> +      "default-src 'self'; img-src *; script-src 'self' 'unsafe-eval' https://challenges.cloudflare.com/; style-src 'self' 'unsafe-inline'; frame-src https://challenges.cloudflare.com https://youtube
can we do the check env and only do unsafe if its not prod?

2022-12-29 23:16 UTC, Huskydog9988 commented on apps/web/pages/auth/login.tsx
> +        provider: 'FaceBook',
```suggestion
        provider: 'Facebook',
```

2022-12-29 23:16 UTC, Huskydog9988 commented on apps/web/types/next-auth.d.ts
> +}
use the prisma type?

2022-12-29 23:16 UTC, Huskydog9988 commented on apps/web/utils/helpers/apiHelper.ts
>  const handleUploadFileLogic = async (
remove this file? its unsed

2022-12-29 23:16 UTC, Huskydog9988 commented on apps/web/utils/links.ts
> +export const discord = 'https://discord.gg/qJWcsS9TyT';
because /chat redirects to the discord invite
```suggestion
export const discord = '/chat';
```

2022-12-29 23:16 UTC, Huskydog9988 commented on packages/eslint-config-custom/index.js
> +    es6: true,
the ts target is 2017, and es6 is older than that i think yea?

2022-12-29 23:51 UTC, ceriddenn commented on apps/web/utils/helpers/apiHelper.ts
>  const handleUploadFileLogic = async (
the checkUrl function is used but the other is not. I removed the function that wasn't user anymore.

2022-12-29 23:54 UTC, ceriddenn commented on packages/eslint-config-custom/index.js
> +    es6: true,
I have no idea...

2022-12-30 00:30 UTC, tsundDEV commented on .vscode/settings.json
> +  "cSpell.language": "en,en-GB,en-US"
My error, remove cSpell extension list

2022-12-30 00:38 UTC, tsundDEV approved these changes

2022-12-31 15:46 UTC, Huskydog9988 approved these changes

2022-12-31 15:47 UTC, Huskydog9988 commented on apps/web/components/TurnstileWidget.tsx
> +          siteKey={'1x00000000000000000000AA'}
will solve later

2022-12-31 15:48 UTC, Huskydog9988 commented on apps/web/components/dashboard/status/Account.tsx
> +      });
will solve later

2022-12-31 15:48 UTC, Huskydog9988 commented on apps/web/components/dashboard/status/Maintenance.tsx
> +        maintenance: data?.maintenance as boolean,
will solve later

2022-12-31 15:48 UTC, Huskydog9988 commented on apps/web/components/dashboard/status/Upload.tsx
> +      });
will solve later

2022-12-31 15:48 UTC, Huskydog9988 commented on apps/web/next.config.js
> +      "default-src 'self'; img-src *; script-src 'self' 'unsafe-eval' https://challenges.cloudflare.com/; style-src 'self' 'unsafe-inline'; frame-src https://challenges.cloudflare.com https://youtube
will solve later

2022-12-31 15:48 UTC, Huskydog9988 commented on apps/web/components/dashboard/status/WaldoSite.tsx
> +    } else if (change == 1) {
will solve later

2022-12-31 15:48 UTC, Huskydog9988 commented on .vscode/settings.json
> +  "cSpell.language": "en,en-GB,en-US"
will solve later

2022-12-31 15:48 UTC, merged