Create CONTRIBUTING.md
waldo-vision/waldo pull request #65
Opened 2022-12-31 18:11 UTC by jaredb1011

2022-12-31 18:16 UTC, Huskydog9988 requested changes

2022-12-31 18:16 UTC, Huskydog9988 commented on CONTRIBUTING.md
> +https://docs.waldo.vision/docs/contributing/
i think this is the correct path
```suggestion
https://docs.waldo.vision/en/getting-started
```

2022-12-31 18:21 UTC, jaredb1011 commented on CONTRIBUTING.md
> +https://docs.waldo.vision/docs/contributing/
getting a 404 for that path

2022-12-31 18:21 UTC, Huskydog9988 commented on CONTRIBUTING.md
> +https://docs.waldo.vision/docs/contributing/
i thought you were entering the path for the new docs, my mistake

2023-01-01 02:55 UTC, tsundDEV approved these changes

2023-01-01 02:55 UTC, Huskydog9988 approved these changes

2023-01-01 02:55 UTC, merged