Wip/web rework
waldo-vision/waldo pull request #74
Opened 2023-01-04 14:48 UTC by tsundDEV

2023-01-04 16:38 UTC, ceriddenn submitted a review, later dismissed

2023-01-04 16:38 UTC, ceriddenn commented on apps/web/additional.d.ts
> +    NEXT_PUBLIC_NODE_ENV: string;
We should prolly change this to just “NEXT_ENV” sooner than later

2023-01-04 16:53 UTC, Huskydog9988 commented on apps/web/additional.d.ts
> +    NEXT_PUBLIC_NODE_ENV: string;
NODE_ENV is the standard in js, and some packages build differently depending on it. So in my mind NEXT_ENV doesn't provide anything unless next acts differently.

2023-01-04 17:20 UTC, ceriddenn commented on apps/web/additional.d.ts
> +    NEXT_PUBLIC_NODE_ENV: string;
Sorry totally meant NODE_ENV just meant to remove the NEXT_PUBLIC part in front of it

2023-01-04 18:47 UTC, Huskydog9988 commented on apps/web/additional.d.ts
> +    NEXT_PUBLIC_NODE_ENV: string;
It's fine, just wanted to make sure I wasn't missing something.

2023-01-04 18:48 UTC, ceriddenn commented on apps/web/additional.d.ts
> +    NEXT_PUBLIC_NODE_ENV: string;
All good

2023-01-05 23:33 UTC, Huskydog9988 requested changes

2023-01-05 23:33 UTC, Huskydog9988 commented on apps/web/additional.d.ts
> +    NEXT_PUBLIC_NODE_ENV: string;
```suggestion
    NODE_ENV: string;
```

2023-01-05 23:33 UTC, Huskydog9988 commented on apps/web/server/trpc/router/user.ts
> +              role: input.filterRoles as Roles,
is this the only way?

2023-01-05 23:33 UTC, Huskydog9988 commented on apps/web/utils/zod/dash.ts
> +  image: z.string().nullable().optional(),
doesn't optional and nullable in zod do the same thing?

2023-01-05 23:33 UTC, Huskydog9988 commented on docs/src/config.ts
> +    src: '../public/android-chrome-256x256.png',
does this work?

2023-01-05 23:33 UTC, Huskydog9988 commented on docs/src/pages/en/introduction.md
> +To start contributing to Waldo, check our [getting started](/en/getting-started) page. It provides all the documentation on how to setup Waldo so you can start contributing.
getting started should work, and keeps it a realative path

2023-01-05 23:33 UTC, Huskydog9988 commented on turbo.json
> +        "NEXT_PUBLIC_NODE_ENV"
```suggestion
        "NODE_ENV"
```

2023-01-05 23:36 UTC, jaredb1011 approved these changes

2023-01-06 00:25 UTC, Huskydog9988 approved these changes

2023-01-06 00:25 UTC, Huskydog9988 commented on docker/cockroach/.gitignore
> +!.gitignore
why not just use the root git ignore?

2023-01-06 00:33 UTC, tsundDEV commented on docker/cockroach/.gitignore
> +!.gitignore
I want to have this directory showing on the git

2023-01-06 00:34 UTC, ceriddenn approved these changes

2023-01-06 00:40 UTC, merged